import Head from "next/head";
import Navbar from "../components/navbar2";
import About from "./about2";
import HomePage from "./homePage2";
import Example from "./idea2";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hashtagpage-Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Navbar />
      <HomePage />
      <About />
      <Example /><br></br><br></br>
      <Footer />
    </div>
  );
}