import Head from "next/head";
import Navbar from "../components/navbar";
import About from "./about";
import HomePage from "./homePage";
import Join from "./join";
import Example from "./idea";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hashtagpage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Navbar />
      <HomePage />
      <About />
      <Example />
      <Join />
      <Footer />
    </div>
  );
}
